title: Branden Lamb
author: 
  name: brandenlamb
  email: brandenlamb@icloud.com
description: 
  Coming soon. 
url: brandenlamb.github.io 
links: 
  - title: LinkedIn
    link: https://www.linkedin.com/in/brandenlamb/
  - title: GitHub
    link: https://github.com/brandenlamb
remote_theme: jekyll/minima
minima: 
  skin: dark
