title: Branden Lamb
author: 
  name: brandenlamb
  email: brandenlamb@icloud.com
description: 
  Coming soon. 
url: brandenlamb.github.io 
linkedin_username: brandenlamb
github_username: brandenlamb
remote_theme: jekyll/minima
minima: 
  skin: dark
