title: Branden Lamb
author: 
  email: brandenlamb@icloud.com
description: > 
  Coming soon. 
  <br><br>
  <a href="https://www.linkedin.com/in/brandenlamb/">LinkedIn</a> 
  <br><br>
  <a href="mailto:brandenlamb@icloud.com">Send me an email</a>

collections: 
  projects:
    output: true
    permalink: /:collection/:title
  
theme: jekyll-theme-minimal
